name: Develop Build and Test
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - 'develop'
      - 'ci/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dummy-test:
    name: Dummy action
    runs-on: ubuntu-latest

    steps:
      - name: Dummy Action Test
        run: |
          echo "${{ github.workflow }}-${{ github.ref }}"
          echo "'[${{ vars.MAINTAINER_USERNAME }}]'"

  lint:
    name: Lint
    uses: ./.github/workflows/lint-workflow.yml

  testing:
    name: Testing
    uses: ./.github/workflows/testing-workflow.yml
    needs: [lint]
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  coverage:
    name: Coverage
    uses: ./.github/workflows/coverage-workflow.yml
    needs: [ testing ]
    with:
      create-badge: true
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  build:
    name: Build
    uses: ./.github/workflows/build-app-workflow.yml
    needs: [ testing ]
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  cleanup:
    name: Cleanup
    uses: ./.github/workflows/cleanup-workflow.yml
    needs: [ coverage ]
    if: always()

  coverage-badge:
    name: Create Badge
    needs: [ coverage ]
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        id: clone-repo
        uses: actions/checkout@v3

      - name: Checkout badges branch to a badges directory nested inside first checkout
        uses: actions/checkout@v3
        with:
          ref: badges
          path: badges

      - name: Download coverage result
        uses: actions/download-artifact@v3
        with:
          name: coverage-result
          path: app/build/reports/jacoco/jacocoDebugReport/

      - name: Create coverage badge
        id: jacoco-badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true
          jacoco-csv-file: app/build/reports/jacoco/jacocoDebugReport/jacocoDebugReport.csv
          coverage-badge-filename: develop-jacoco.svg
          summary-filename: develop-coverage-summary.json
          intervals: 90 80 70 60 50 0
