name: Develop Build
on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/readme-images/*'
    branches:
      - 'develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint Develop
    uses: ./.github/workflows/lint-workflow.yml

  testing:
    name: Testing Develop
    uses: ./.github/workflows/testing-workflow.yml
    needs: [ lint ]
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  coverage:
    name: Coverage Develop
    uses: ./.github/workflows/coverage-workflow.yml
    needs: [ testing ]
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  build:
    name: Build Develop App
    uses: ./.github/workflows/build-app-workflow.yml
    needs: [ coverage ]
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  cleanup:
    name: Cleanup Develop
    uses: ./.github/workflows/cleanup-workflow.yml
    needs: [ coverage ]
    if: always()

  coverage-badge:
    name: Coverage Badge
    needs: [ coverage ]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        id: clone-repo
        uses: actions/checkout@v3

      - name: Checkout badges branch to a badges directory nested inside first checkout
        uses: actions/checkout@v3
        with:
          ref: badges
          path: badges

      - name: Download coverage result
        uses: actions/download-artifact@v3
        with:
          name: coverage-result
          path: app/build/reports/jacoco/jacocoDebugReport/

      - name: Create coverage badge
        id: jacoco-badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-summary: true
          jacoco-csv-file: app/build/reports/jacoco/jacocoDebugReport/jacocoDebugReport.csv
          coverage-badge-filename: develop-jacoco.svg
          summary-filename: develop-coverage-summary.json
          intervals: 90 80 70 60 50 0

      - name: Commit and push the coverage badges and summary file
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd badges
          if [[ `git status --porcelain *.svg *.json` ]]; then
            git config user.name 'github-actions'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add *.svg *.json
            git commit -m "Autogenerated jacoco coverage badges"
            git push
          fi
