name: Trigger Release
on:
  workflow_dispatch:
    inputs:
      extra-version:
        description: 'Extra version after v*.*.* (eg: input -alpha1 will create v*.*.*-alpha1)'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-trigger-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  create-release-branch:
    name: Create Release Branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        id: clone-repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract Version Number
        id: version
        uses: ./.github/actions/extract-version-properties
        with:
          extra-version: ${{ inputs.extra-version }}

      - id: foo
        uses: ./.github/actions/hello-world-composite-action@v1
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Check version
        id: check-version
        run: |
          echo "test:${{ steps.version.output.test12312 }}"
          echo "full-version:${{ steps.version.output.version }}"
          echo "random:${{ steps.version.output.random-number }}"
          echo "major:${{ steps.version.output.major }}"
          echo "minor:${{ steps.version.output.minor }}"
          echo "patch:${{ steps.version.output.patch }}"
          echo "extra:${{ steps.version.output.extra }}"

      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

#      - name: Create Release Branch
#        id: release-branch
#        run: |
#          git config user.name 'github-actions'
#          git config user.email 'github-actions@github.com'
#          TAG_RELEASE="ci-${{ steps.version.outputs.version }}"
#          BRANCH_RELEASE="release/$TAG_RELEASE"
#          git checkout -b "$BRANCH_RELEASE"
#          git push --set-upstream origin "$BRANCH_RELEASE"
#          echo "tag=$TAG_RELEASE" >> $GITHUB_OUTPUT
#          echo "branch=$BRANCH_RELEASE" >> $GITHUB_OUTPUT
#
#      - name: Checkout Main Branch
#        uses: actions/checkout@v3
#        with:
#          ref: ci/dummy-merge-target
#          fetch-depth: 0
#
#      - name: Checkout Release Branch
#        uses: actions/checkout@v3
#        with:
#          ref: ${{ steps.release-branch.outputs.branch }}
#          fetch-depth: 0
#
#      - name: Merge to Main Branch
#        id: merge-release-branch
#        run: |
#          git config user.name 'github-actions'
#          git config user.email 'github-actions@github.com'
#          git checkout "${{ steps.release-branch.outputs.branch }}"
#          git checkout ci/dummy-merge-target
#          git merge "${{ steps.release-branch.outputs.branch }}"
#          git tag -s -a "${{ steps.release-branch.outputs.tag }}" -m "Release ${{ steps.release-branch.outputs.tag }}"
#          git push --follow-tags