name: Build and Test
on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - 'develop'
      - 'ci/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  JAVA_VERSION: 11
  GRADLE_VERSION: 7.4

permissions:
  contents: read

jobs:
  testing:
    name: Testing
    uses: ./.github/workflows/testing-workflow.yml
    with:
      java-version: 11
      gradle-version: 7.4
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  lint:
    name: Lint
    uses: ./.github/workflows/lint-workflow.yml
    with:
      java-version: 11
      gradle-version: 7.4
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  build:
    name: Build
    uses: ./.github/workflows/build-app-workflow.yml
    needs: [testing, lint]
    with:
      java-version: 11
      gradle-version: 7.4
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  coverage-report:
    name: Coverage Report
    needs: [testing]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Clone repo
        id: clone-repo
        uses: actions/checkout@v3

      - name: Download coverage result
        uses: actions/download-artifact@v3
        with:
          name: coverage-result
          path: app/build/reports/jacoco/jacocoDebugReport/

      - name: Add coverage to PR
        id: jacoco-report
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/app/build/reports/jacoco/jacocoDebugReport/jacocoDebugReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: "Coverage report"
          update-comment: true

      - name: Check coverage threshold
        id: jacoco-threshold
        run: |
          FAILED_OVERALL_COVERAGE=false
          FAILED_CHANGED_FILE_COVERAGE=false
          if [[ ${{ steps.jacoco-report.outputs.coverage-overall }} < 80 ]]; then PASS_OVERALL_COVERAGE=true;echo "::error::Overall Coverage Below Threshold"; fi
          if [[ ${{ steps.jacoco-report.outputs.coverage-changed-files }} < 80 ]]; then PASS_CHANGED_FILE_COVERAGE=true;echo "::error::Changed File Coverage Below Threshold"; fi
          if [[ FAILED_OVERALL_COVERAGE || FAILED_CHANGED_FILE_COVERAGE ]]; then exit 1; fi
          

