name: Release Build
on:
  push:
    tags:
      - v*
      - ci*

concurrency:
  group: ${{ github.workflow }}-release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dummy:
    name: Dummy Job
    runs-on: ubuntu-latest

    steps:
      - name: Testing Caller
        run: |
          echo "Running Here"

      - name: Get tag name
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.repository == 'ngengs/daily-image-app-android' }}
        run: |
          set -x
          VERSION_TAG=${GITHUB_REF/refs\/tags\//}
          echo ${VERSION_TAG}
          NO_CI_VERSION_TAG=${VERSION_TAG/ci-/}
          CLEAN_VERSION_TAG=${NO_CI_VERSION_TAG/v/}
          echo ${CLEAN_VERSION_NAME}

#  build:
#    name: Build
#    uses: ./.github/workflows/build-app-workflow.yml
#    if: ${{ startsWith(github.ref, 'refs/tags/') && github.repository == 'ngengs/daily-image-app-android' }}
#    with:
#      signed-build: true
#    secrets:
#      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES_RELEASE }}
#      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
#      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
#      SIGNING_KEY_STORE_PASSWORD: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}
#      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

