name: PR Build and Test
on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - 'develop'
      - 'ci/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint-workflow.yml
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  testing:
    name: Testing
    uses: ./.github/workflows/testing-workflow.yml
    needs: [lint]
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  build:
    name: Build
    uses: ./.github/workflows/build-app-workflow.yml
    needs: [testing]
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  coverage:
    name: Coverage
    uses: ./.github/workflows/coverage-workflow.yml
    needs: [testing]
    with:
      report-pr: true
    secrets:
      SECRET_PROPERTIES_CONFIG: ${{ secrets.CONFIG_SECRETS_PROPERTIES }}

  cleanup:
    name: Cleanup
    uses: ./.github/workflows/cleanup-workflow.yml
    needs: [coverage]
    if: always()

          

