name: Build App

on:
  workflow_call:
    inputs:
      env-file-path:
        description: ".env file location"
        required: false
        default: ./.github/variables/default_github_action.env
        type: string

    secrets:
      SECRET_PROPERTIES_CONFIG:
        description: "secret.properties hash"
        required: true

jobs:

  build:
    name: Build
    if: inputs.signed-build == false
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        id: clone-repo
        uses: actions/checkout@v3

      - name: Extract Env
        uses: ./.github/actions/using-env-variables
        with:
          env-file-path: ${{ inputs.env-file-path }}

      - name: Configuration
        uses: ./.github/actions/config-build-app
        with:
          secrets-properties-config: ${{ secrets.SECRET_PROPERTIES_CONFIG }}
          java-version: ${{ env.JAVA_VERSION }}
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Dependency Review
        uses: actions/dependency-review-action@v3

      - name: Build App
        run: ./gradlew assemble

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Cleanup
        run: rm -rf secrets.properties