name: Coverage

on:
  workflow_call:
    inputs:
      env-file-path:
        description: ".env file location"
        required: false
        default: ./.github/variables/default_github_action.env
        type: string

    secrets:
      SECRET_PROPERTIES_CONFIG:
        description: "secret.properties hash"
        required: true

jobs:
  coverage:
    name: Check Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        id: clone-repo
        uses: actions/checkout@v3

      - name: Extract Env
        uses: ./.github/actions/using-env-variables
        with:
          env-file-path: ${{ inputs.env-file-path }}

      - name: Configuration
        uses: ./.github/actions/config-build-app
        with:
          secrets-properties-config: ${{ secrets.SECRET_PROPERTIES_CONFIG }}
          java-version: ${{ env.JAVA_VERSION }}
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Download unit test java build artifact
        uses: actions/download-artifact@v3
        with:
          name: unit-test-java-class-build
          path: app/build/intermediates/javac/

      - name: Download unit test kotlin build artifact
        uses: actions/download-artifact@v3
        with:
          name: unit-test-kotlin-class-build
          path: app/build/tmp/kotlin-classes/

      - name: Download unit test result artifact
        uses: actions/download-artifact@v3
        with:
          name: unit-test-result
          path: app/build/outputs/unit_test_code_coverage/

      - name: Download instrument test result artifact
        uses: actions/download-artifact@v3
        with:
          name: instrument-test-result-31
          path: app/build/outputs/code_coverage/debugAndroidTest/

      - name: Check coverage
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jacocoDebugReport
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Upload coverage result
        uses: actions/upload-artifact@v3
        with:
          name: coverage-result
          path: app/build/reports/jacoco/jacocoDebugReport/
          if-no-files-found: error

