name: Lint

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number
      gradle-version:
        required: true
        type: number

    secrets:
      secret-properties-config:
        description: "secret.properties hash"
        required: true

jobs:
  ktlint:
    name: Check Kotlin Style
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        id: clone-repo
        uses: actions/checkout@v3

      - name: Configuration
        uses: ./.github/actions/config-build-app
        with:
          secrets-properties-config: ${{ secrets.secret-properties-config }}
          java-version: ${{ inputs.java-version }}
          gradle-version: ${{ inputs.gradle-version }}

      - name: Check code style
        run: ./gradlew ktlintGenerateBaseline

      - name: Report code style
        uses: ScaCap/action-ktlint@1.5.1
        if: success() || failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          android: true
          baseline: app/build/reports/ktlint/config/baseline.xml
          reporter: github-check
          fail_on_error: true