name: Lint

on:
  workflow_call:

jobs:
  ktlint:
    name: Kotlin Code Style
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        id: clone-repo
        uses: actions/checkout@v3

      - name: Check code style
        if: ${{ github.event_name != 'pull_request' || github.event_name != 'pull_request_target' }}
        run: ./ktlint '**/**src/**/*.kt'